Refactor
PrashantSakre/easy-mql-webtool pull request #6
Opened 2021-02-28 05:54 UTC by PrashantSakre

2021-02-28 07:11 UTC, vivek-shrikhande commented on static/java_script/ace-script.js
>  }
Add an empty line at the end of file.

2021-02-28 07:13 UTC, vivek-shrikhande requested changes

2021-02-28 07:13 UTC, vivek-shrikhande commented on static/main.css
>  }
Add an empty line at the end of file.

2021-02-28 07:13 UTC, vivek-shrikhande commented on templates/home.html
>  {% endblock content %}
Add an empty line at the end of file.

2021-03-10 09:42 UTC, PrashantSakre commented on static/main.css
>  }
Added..

2021-03-10 11:21 UTC, vivek-shrikhande approved these changes

2021-03-10 12:11 UTC, merged